title = 'Cloud Security Corner'
baseURL = 'cloudsecuritycorner.com'

defaultContentLanguage = 'en'
languageCode = 'en-us'
enableInlineShortcodes = true
googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false

[minify]
  disableHTML = true