[[main]]
identifier = 'home'
name = 'Home'
pre = "<i class='icon icon-home'></i>"
url = '/'
weight = 1

[[main]]
identifier = 'docs'
name = 'Documentation'
pre = "<i class='icon icon-book'></i>"
url = '/docs/'
weight = 2

[[main]]

identifier = 'Roadmap'
name = 'roadmap'
pre = "<i class='icon icon-book'></i>"
url = '/roadmap/'
weight = 3


[[main]]

identifier = 'Quiz'
name = 'Quiz'
pre = "<i class='icon icon-book'></i>"
url = '/Quiz/'
weight = 4