description = 'Cloud Security'

author = 'CloudNativeFolks'
authorURL = 'https://discord.gg/rEvr7vq'

currentYear = 2023
# projectStartYear = 2020


twitterURL = 'https://twitter.com/i/communities/1499311438745468931'
githubURL = 'https://github.com/cloudseccorner'
youtubeURL = 'https://www.youtube.com/@cloudsecuritycorner'

githubRepo = 'cloudseccorner/quickstart'





