title = "Cloud Security Corner"
baseURL = "https://cloudsecuritycorner.com"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "CloudNativeFolks"

enableGitInfo = true
summaryLength = 15

[markup.highlight]
style = "paraiso-dark"

[params]
font_awesome_version = "5.12.0"
description = " **Securing the Cloud, Together!** "
herodescription = "A vibrant community for cloud security enthusiasts.Sharing knowledge, best practices, and expert insights.Securing the cloud, one discussion at a time."
favicon = "favicon.png"
repositoryUrl = "https://github.com/cloudseccorner/website"
contentDir = "/content/"

[params.logos]
navbar = "cncf-color.png"

[permalinks]
blog = "/blog/:year/:01/:02/:title/"

[[params.colors.extra]]
name = "twitter-blue"
hex = "#00aced"

[[params.social]]
name = "Twitter"
color = "twitter-blue"
url = "https://twitter.com/sangamtwts"
icon = "fab fa-twitter"

[[params.fonts]]
name = "Fira Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Fire Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"


[[menu.main]]
name = "About"
identifier ="about"
url = "#"
weight = 10

[[menu.main]]
name = "About the CSC"
parent = "about"
url = "/about/overview"
weight = 20


[[menu.main]]
name = "Code of conduct"
parent = "about"
url = "https://github.com/opencontainers/.github/blob/master/CODE_OF_CONDUCT.md"
post = "external"
weight = 30

[[menu.main]]
name = "Leadership"
parent = "about"
url = "/about/tob"
weight = 50

[[menu.main]]
name = "Security disclosure"
parent = "about"
url = "/about/security-disclosure"
weight = 70

[[menu.main]]
name = "Community"
identifier ="community"
url = "#"
weight = 20

[[menu.main]]
name = "Overview"
parent ="community"
url = "/community/overview"
weight = 10

[[menu.main]]
name = "Roadmap"
parent = "community"
url = "/community/roadmap"
weight = 20

[[menu.main]]
name = "Join"
identifier ="join"
url = "/join"
weight = 30

[[menu.main]]
name = "Blog"
identifier ="blog"
url = "/posts/blog"
weight = 40

[[menu.main]]
name = "News"
identifier ="news"
url = "#"
weight = 50

[[menu.main]]
name = "Announcements"
parent ="news"
url = "/posts/announcements/"
weight = 10

[[menu.main]]
name = "In the news"
parent ="news"
url = "/posts/news/"
weight = 20

[[menu.main]]
name = "FAQ"
identifier ="faq"
url = "/faq"
weight = 60



[[menu.main]]
name = "Contact us"
identifier ="contact"
url = "/contact"
weight = 90
